apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "replicasets", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
