apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: noor
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
