apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
